global:
  scrape_interval:     10s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'proposta'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['propostas:8080']